import { createHash } from "node:crypto";

import type { StoreData } from "@/lib/types";

function hash(password: string) {
  return createHash("sha256").update(password).digest("hex");
}

export const seedData: StoreData = {
  users: [
    {
      id: "user-farmer-1",
      name: "Aarav Patel",
      email: "farmer@farmmarket.local",
      passwordHash: hash("demo123"),
      role: "farmer",
      location: "Anand, Gujarat",
      farmType: "Organic vegetables",
      languages: ["English", "Hindi", "Gujarati"],
      rating: 4.8,
      approved: true,
      createdAt: "2026-03-20",
    },
    {
      id: "user-buyer-1",
      name: "Maya Foods",
      email: "buyer@farmmarket.local",
      passwordHash: hash("demo123"),
      role: "buyer",
      location: "Ahmedabad, Gujarat",
      businessType: "Restaurant chain",
      languages: ["English", "Hindi"],
      rating: 4.6,
      approved: true,
      createdAt: "2026-03-20",
    },
    {
      id: "user-admin-1",
      name: "Rohan Mehta",
      email: "admin@farmmarket.local",
      passwordHash: hash("demo123"),
      role: "admin",
      location: "Surat, Gujarat",
      languages: ["English", "Hindi"],
      rating: 5,
      approved: true,
      createdAt: "2026-03-20",
    },
    {
      id: "user-farmer-2",
      name: "Kiran Farms",
      email: "pending-farmer@farmmarket.local",
      passwordHash: hash("demo123"),
      role: "farmer",
      location: "Nashik, Maharashtra",
      farmType: "Fruit orchard",
      languages: ["English", "Hindi", "Marathi"],
      rating: 4.4,
      approved: false,
      createdAt: "2026-03-25",
    },
  ],
  products: [
    {
      id: "product-1",
      farmerId: "user-farmer-1",
      title: "Vine Tomatoes",
      category: "Vegetables",
      price: 48,
      quantity: 120,
      unit: "kg",
      harvestDate: "2026-03-25",
      images: ["/produce-placeholder.svg"],
      location: "Anand, Gujarat",
      freshnessNote: "Freshly harvested today",
      organic: true,
      deliveryOptions: ["self", "platform"],
      sustainabilityScore: 92,
      createdAt: "2026-03-24",
    },
    {
      id: "product-2",
      farmerId: "user-farmer-1",
      title: "Baby Spinach",
      category: "Vegetables",
      price: 34,
      quantity: 48,
      unit: "kg",
      harvestDate: "2026-03-26",
      images: ["/produce-placeholder.svg"],
      location: "Anand, Gujarat",
      freshnessNote: "Only 5kg batches packed per hour to keep leaves crisp",
      organic: true,
      deliveryOptions: ["platform"],
      sustainabilityScore: 88,
      createdAt: "2026-03-25",
    },
    {
      id: "product-3",
      farmerId: "user-farmer-2",
      title: "Alphonso Mangoes",
      category: "Fruits",
      price: 120,
      quantity: 75,
      unit: "kg",
      harvestDate: "2026-03-24",
      images: ["/produce-placeholder.svg"],
      location: "Nashik, Maharashtra",
      freshnessNote: "Sweet batch, orchard sorted for restaurant plating",
      organic: false,
      deliveryOptions: ["self"],
      sustainabilityScore: 81,
      createdAt: "2026-03-23",
    },
  ],
  offers: [
    {
      id: "offer-1",
      productId: "product-1",
      buyerId: "user-buyer-1",
      farmerId: "user-farmer-1",
      offeredPrice: 44,
      status: "pending",
      messages: [
        {
          id: "message-1",
          senderId: "user-buyer-1",
          text: "Need 35kg delivered to our central kitchen twice this week.",
          createdAt: "2026-03-26 09:10",
        },
        {
          id: "message-2",
          senderId: "user-farmer-1",
          text: "I can do platform delivery and confirm same-day dispatch.",
          createdAt: "2026-03-26 09:28",
        },
      ],
      createdAt: "2026-03-26 09:10",
      updatedAt: "2026-03-26 09:28",
    },
  ],
  reviews: [],
  orders: [
    {
      id: "order-1",
      offerId: "offer-old-1",
      productId: "product-2",
      buyerId: "user-buyer-1",
      farmerId: "user-farmer-1",
      quantity: 20,
      unit: "kg",
      total: 960,
      status: "in-transit",
      deliveryType: "platform",
      deliveryStatus: "Driver assigned",
      address: "Maya Foods, Prahlad Nagar, Ahmedabad",
      eta: "2 hours",
      paymentProvider: "razorpay",
      paymentStatus: "paid",
      createdAt: "2026-03-25 17:30",
    },
  ],
  passwordResets: [],
};
